### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: changes$

### ISSUE THREAD

**Issue by hputzek** [PVermeer/dexie-rxjs-addon#1]
# Hi @PVermeer 

Thanks for creating this library!
I'm really keen on using it in my project, but I did not manage to make it work yet. 😔

## Error description

When I add the plugin I get an error immediately after the call to `dexieRxjs(this).`

> Uncaught TypeError: Cannot redefine property: changes$

The error is thrown at `@pvermeer/dexie-rxjs-addon/dist/es6/add-properties.js:47`:
```javascript
export function addTable$(db) {
    Object.defineProperty(db.Table.prototype, '$', {
        get: function () {
            if (!this._table$) {
                /**
                 * Represents the current state of the table.
                 * On first subscription (get $) emit fresh data then sub to changes.
                 */
                this._table$ = db.changes$.pipe(filter(x => x.some(y => y.table === this.name)), startWith([]), flatMap(() => tslib_1.__awaiter(this, void 0, void 0, function* () { return this.toArray(); })), distinctUntilChanged(isEqual), shareReplay());
            }
            return this._table$;
        }
    });
}
```

## this is my database class:

```typescript
import Dexie from "dexie";
import dexieCloud from "dexie-cloud-addon";
import { Device, IDevice } from "./Device";
import { dexieRxjs } from "@pvermeer/dexie-rxjs-addon";

class AppDatabase extends Dexie {
  public devices: Dexie.Table<IDevice, string>;

  constructor() {
    super("PixelcrasherDb", { addons: [dexieCloud, dexieRxjs] });
    dexieRxjs(this);
    //
    // Define tables and indexes
    //
    this.version(1).stores({
      devices:
        "@id, meta.title, meta.description, specs.ledCount, specs.ledCountPerMeter, controlParameters.universe",
    });

    // This will make it possible to call functions defined in the Device Class
    // directly on retrieved database objects.
    this.devices.mapToClass(Device);
  }
}

```
### Library versions:
```json
{
    "dexie": "^3.0.3",
    "dexie-cloud-addon": "^1.0.0-alpha.7",
    "rxjs": "^6.6.7",
    "@pvermeer/dexie-rxjs-addon": "^1.0.0-beta.1",
}
```

I tried it without the `dexie-cloud-addon` but the result stays the same.
When I omit the call to `dexieRxjs(this);` the `$`-property is attached to all tables, but the function (`get()`, `toArray()`...) are missing (which makes sense I guess 🙃)

I would be really happy if you have any idea what I did wrong or if there is a bug in the library itself.

Thanks, Hendrik

**Comment by PVermeer** [comment]
I think I did a rewrite of the addon in a later beta because I wasn't happy with some things. Seems like you're using the first version. Also haven't tested much with the final release of Dexie 3. Could you try the latest version? At the moment I'm not well so it might be a while till I pick development up again.

**Comment by hputzek** [comment]
Hi @PVermeer 

Thanks for taking the time to answer even though you're not well at the moment!

You were indeed right: I used the `1.0.0-beta.1` version from npm instead of the most current one.
I switched to `1.0.0-beta.18` and now the error is gone.

I did not test the whole functionality but I am able to create an observable now 👍

Thanks four the hint!

Greetings, Hendrik
